channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.8.3
  - notebook=7.1.1
  - numpy=1.26.4
  - optuna=3.6.0
  - pandas=2.2.2
  - pip=25.2
  - pytest=8.4.1
  - python=3.12.2
  - scikit-learn=1.4.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - setuptools=80.9.0
  - tqdm=4.66.4
  - pip:
      - torch==2.8.0+cu126
      - mkdocs==1.6.1
      - mkdocstrings-python==1.16.12
      - pytorch-lightning==2.5.3
      - -e .
