site_name: My Docs
theme: readthedocs
nav:
  - Home: index.md
  - API: api.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          show_root_full_path: true
          show_root_toc_entry: true
          show_source: false
          show_signature: true